# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: test the workflow

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install sphinx toolset
      run: >-
        python -m
        pip install
        sphinx
        sphinx-argparse
        --user

    - name: Install tldr dependencies
      run: >-
        python -m
        pip install
        -r
        requirements.txt
        --user

    - name: Generate the manpage
      run: (cd docs && make man)

    - name: Install pep517
      run: >-
        python -m
        pip install
        pep517
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        pep517.build
        --source
        --binary
        --out-dir dist/
        .

